# variables in the pipeline
# dockerId = dockerId where the image is published
# dockerPassword = password to connect to dockerHub with the dockerId

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'kossmonautes-web:$(build.buildId)'

steps:
- script: docker build -f frontend/kossmonautes-web/Dockerfile -t $(dockerId)/$(imageName) frontend/kossmonautes-web/.
  displayName: 'docker build'
- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)
