# variables in the pipeline
# dockerId = dockerId where the image is published
# dockerPassword = password to connect to dockerHub with the dockerId
variables:
    webImageName: 'kossmonautes-web:$(build.buildId)'
    apiImageName: 'kossmonautes-web:$(build.buildId)'
    dockerbuildCommand: 'docker build -f $(baseFolder)/Dockerfile -t $(dockerId)/$(imageName) $(baseFolder)/.'
    jobsVmImage: 'Ubuntu 16.04'
jobs:
- job: kossmonautes_web_build
  variables:
    imageName: $(webImageName)
    baseFolder: 'frontend/kossmonautes-web'
  pool:
    vmImage: '$(jobsVmImage)'
  steps:
  - script: $(dockerbuildCommand)

- job: kossmonautes_api_build
  variables:
    imageName: $(apiImageName)
    baseFolder: 'backend/api/Kossmonautes.Api'
  pool:
      vmImage: '$(jobsVmImage)'
  steps:
  - script: $(dockerbuildCommand)
  
- job: push_all_images
  dependsOn:
    - kossmonautes_web_build
    - kossmonautes_api_build
  condition: succeeded()
  pool:
    vmImage: '$(jobsVmImage)'
  steps:
  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(webImageName)
      docker push $(dockerId)/$(apiImageName)
